### ISSUE TITLE
after load files the window grays out

### ISSUE THREAD

**Issue by haiyan-MS** [Sebastian-Vaca/diaPASEF_Viz_Tool#1]
HI Sebastian:

Thank you for showing me this nice software. I tried it on my laptop. But once I uploaded required report.tsv and the metadata file, it grays out. Please see this screen shot.
![image](https://github.com/Sebastian-Vaca/diaPASEF_Viz_Tool/assets/91212783/820ded80-1c94-4e1a-aa43-b268d8bd6ec8)

**Comment by Sebastian-Vaca** [comment]
Hi, thanks for the feedback. Would it be possible to share the file with me so I can test it?

**Comment by Sebastian-Vaca** [comment]
Explanation of this here: https://github.com/Sebastian-Vaca/diaPASEF_Viz_Tool/issues/2
