### ISSUE TITLE
"Faceting variables must have at least one value" error

### ISSUE THREAD

**Issue by haiyan-MS** [Sebastian-Vaca/diaPASEF_Viz_Tool#2]
I found another issue in a different set of data: 
![image](https://github.com/Sebastian-Vaca/diaPASEF_Viz_Tool/assets/91212783/1afd64c2-73e6-415b-918b-28ba2a053e13)
 THe error message is as following: 
Listening on http://127.0.0.1:6737
[1] "DIANN"
`summarise()` has grouped output by 'R.Condition', 'EG.ModifiedPeptide'. You
can override using the `.groups` argument.
Joining with `by = join_by(PG.ProteinGroups)`
`summarise()` has grouped output by 'R.Condition', 'R.Replicate'. You can
override using the `.groups` argument.
Joining with `by = join_by(R.Condition, R.Replicate, run, type)`
Warning: Error in : Must request at least one colour from a hue palette.
  190: stop
  189: palette
  188: self$palette
  187: map
  186: self$map
  185: FUN
  184: lapply
  183: map_df
  182: scale$map_df
  181: FUN
  180: lapply
  178: FUN
  177: lapply
  176: ggplot_build.ggplot
  174: print.ggplot
  169: func
  167: f
  166: Reduce
  157: do
  156: hybrid_chain
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$Counts_per_MSRun
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in : Must request at least one colour from a hue palette.
  190: stop
  189: palette
  188: self$palette
  187: map
  186: self$map
  185: FUN
  184: lapply
  183: map_df
  182: scale$map_df
  181: FUN
  180: lapply
  178: FUN
  177: lapply
  176: ggplot_build.ggplot
  174: print.ggplot
  169: func
  167: f
  166: Reduce
  157: do
  156: hybrid_chain
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$Counts_per_MSRun
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: There was 1 warning in `mutate()`.
ℹ In argument: `relative_fraction = 1 - area/max(area, na.rm = T)`.
Caused by warning in `max()`:
! no non-missing arguments to max; returning -Inf
Warning: There was 1 warning in `mutate()`.
ℹ In argument: `rank = max(dt_fraction_plot$rank) * 0.1`.
Caused by warning in `max()`:
! no non-missing arguments to max; returning -Inf
Warning in max(dt_fraction_plot$rank) :
  no non-missing arguments to max; returning -Inf
Warning in max(dt_fraction_plot$rank) :
  no non-missing arguments to max; returning -Inf
Warning in max(dt_fraction_plot$rank) :
  no non-missing arguments to max; returning -Inf
`summarise()` has grouped output by 'rt_bin'. You can override using the
`.groups` argument.
Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
generated.
Warning: Error in combine_vars: Faceting variables must have at least one value
  186: <Anonymous>
  185: signalCondition
  184: signal_abort
  183: rlang::abort
  182: cli::cli_abort
  181: combine_vars
  180: compute_layout
  179: self$facet$compute_layout
  178: setup
  177: layout$setup
  176: ggplot_build.ggplot
  174: print.ggplot
  169: func
  167: f
  166: Reduce
  157: do
  156: hybrid_chain
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$BoxHist_Plot
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>

**Comment by Sebastian-Vaca** [comment]
Hi, thanks for the feedback. Would it be possible to share the file and the metadata file with me so I can test it? Thanks!

**Comment by haiyan-MS** [comment]
[Metadata_template-2023-06-08.csv](https://github.com/Sebastian-Vaca/diaPASEF_Viz_Tool/files/11735235/Metadata_template-2023-06-08.csv)
I can't upload the report file as it is unsupported file time. Please let me know how I can share with you

**Comment by Sebastian-Vaca** [comment]
Thanks! Please send the file to sebastian.vaca.ms@gmail.com. I can take a look at what is happening.

**Comment by haiyan-MS** [comment]
Just shared a file with you
________________________________

**Comment by Sebastian-Vaca** [comment]
Thanks for sending the file. Your file has the following problems. All Protein names and gene names are blank and I see that you are not working with a Human proteome. So I think there might be an issue with the parsing of the FASTA file. Since DIA-NN doesn't have the gene names it can't validate the data at the gene level. 
In your report all gene group q-values (GG.Q.Value column) and protein q-values (Protein.Q.Value column) are equal to 1. The Shiny App filters out GG.Q.Value  and Protein.Q.Value values higher than 0.01. So in this case all rows in your file are removed. That's why the App is not showing any plot.

I am guessing this is due to an error in the parsing of the FASTA file.

**Comment by haiyan-MS** [comment]
Thanks! That explains it then. I guess I will try use uniprot in the future

Haiyan
________________________________
